return {
  name = "CraftMind",
  version = "0.2.0",
  files = {
    "README.md",
    "config.lua",
    "boot.lua",
    "core/http.lua",
    "core/logger.lua",
    "core/settings.lua",
    "providers/init.lua",
    "providers/openai_compat.lua",
    "providers/groq.lua",
    "providers/gemini.lua",
    "providers/nvidia.lua",
    "ai/chat.lua",
    "ai/lua_agent.lua",
    "ai/tool_runner.lua",
    "ai/workspace_agent.lua",
    "ai/workspace_tools.lua",
    "docs/index.lua",
    "tools/file.lua",
    "ui/menu.lua",
    "ui/render.lua",
    "apps/setup.lua",
    "apps/chat.lua",
    "apps/agent.lua",
    "turtle/server.lua",
    "client/remote.lua",
  },
}
