return {
  name = "CraftMind",
  version = "0.3.3",
  files = {
    "README.md",
    "config.lua",
    "boot.lua",
    "core/http.lua",
    "core/logger.lua",
    "core/settings.lua",
    "providers/init.lua",
    "providers/openai_compat.lua",
    "providers/groq.lua",
    "providers/gemini.lua",
    "providers/nvidia.lua",
    "ai/chat.lua",
    "ai/lua_agent.lua",
    "ai/tool_runner.lua",
    "ai/context.lua",
    "ai/session.lua",
    "ai/runtime_pipeline.lua",
    "ai/workspace_agent.lua",
    "ai/workspace_tools.lua",
    "ai/orchestrator.lua",
    "identity/init.lua",
    "onboarding/init.lua",
    "docs/index.lua",
    "docs/craftmind.md",
    "docs/agents.md",
    "docs/tools.md",
    "docs/openclaw-adaptation.md",
    "tools/file.lua",
    "ui/menu.lua",
    "ui/render.lua",
    "apps/setup.lua",
    "apps/chat.lua",
    "apps/agent.lua",
    "apps/agents.lua",
    "apps/remote.lua",
    "apps/turtle.lua",
    "turtle/server.lua",
    "client/remote.lua",
  },
}
